Ext.define('LinkExPortal.model.CPDHealthApplicationTemp', {
    extend: 'Ext.data.Model',
    idProperty: 'CPDHealthApplicationFormTempID',
    fields: [
        { name: 'CPDHealthApplicationFormTempID', type: 'auto' },
        { name: 'Description', type: 'auto' },
        { name: 'Firstname', type: 'auto' },
        { name: 'Lastname', type: 'auto' },
        { name: 'PreviousSurname', type: 'auto' },
        { name: 'KnownAs', type: 'auto' },
        { name: 'GenderID', type: 'auto' },
        { name: 'DOB', type: 'auto' },
        { name: 'HomeAddress1', type: 'auto' },
        { name: 'HomeAddress2', type: 'auto' },
        { name: 'HomeCity', type: 'auto' },
        { name: 'HomePostCode', type: 'auto' },
        { name: 'HomeCountryID', type: 'auto' },
        { name: 'WorkAddress1', type: 'auto' },
        { name: 'WorkAddress2', type: 'auto' },
        { name: 'WorkCity', type: 'auto' },
        { name: 'WorkPostcode', type: 'auto' },
        { name: 'WorkCountryID', type: 'auto' },
        { name: 'WardDept', type: 'auto' },
        { name: 'Nationality', type: 'auto' },
        { name: 'EthnicityID', type: 'auto' },
        { name: 'MobileNumber', type: 'auto' },
        { name: 'Telephone', type: 'auto' },
        { name: 'CountryOfBirthID', type: 'auto' },
        { name: 'CountryOfResidence', type: 'auto' },
        { name: 'ProfessionalBodyID', type: 'auto' },
        { name: 'MembershipNumber', type: 'auto' },
        { name: 'MembershipExpiry', type: 'auto' },
        { name: 'MedicalNotes', type: 'auto' },
        { name: 'IsPermanentResident', type: 'auto' },
        { name: 'DateOfFirstEntryToUK', type: 'auto' },
        { name: 'DateOfGrantedResidency', type: 'auto' },
        { name: 'HasCriminalConviction', type: 'auto' },
        { name: 'HasCaution', type: 'auto' },
        { name: 'HasSpentCriminalConviction', type: 'auto' },
        { name: 'HasBindOverOrder', type: 'auto' },
        { name: 'IsCRBChecked', type: 'auto' },
        { name: 'CRBCheckDate', type: 'auto' },
        { name: 'CRBCheckRefNo', type: 'auto' },
        { name: 'ConfirmedAgreement', type: 'auto' },
        { name: 'ConfirmationDate', type: 'auto' },
        { name: 'PersonalStatement', type: 'auto' },
        { name: 'ApplicationStatusID', type: 'auto' },
        { name: 'CourseSessionID', type: 'auto' },
        { name: 'IsConfirmationOfPrerequisites', type: 'auto' },
        { name: 'IsCPDFunded', type: 'auto' },
        { name: 'IsSelfFunded', type: 'auto' },
        { name: 'IsPartFunded', type: 'auto' },
        { name: 'PartFundedPercentage', type: 'auto' },
        { name: 'CanReceiveEmailConfirmation', type: 'auto' },
        { name: 'ChargeNurse', type: 'auto' },
        { name: 'HospitalArea', type: 'auto' },
        { name: 'HasTrustConfirmedCPDFunded', type: 'auto' },
        { name: 'Email', type: 'auto' },
        { name: 'ApplicationDate', type: 'auto' },
        { name: 'PONumber', type: 'auto' },
        { name: 'AccountID', type: 'int' },
        { name: 'TitleID', type: 'auto' },
        { name: 'CourseID', type: 'auto' },
        { name: 'HEIID', type: 'auto' },
        { name: 'SponsorID', type: 'auto' },
        { name: 'CourseSessionText', type: 'auto' }
    ],
    schema: {
        id: 'healthapplicationformtemp',
        namespace: 'LinkExPortal.model',
        proxy: {
            type: 'rest',
            url: 'https://localhost:44306/api/CPDHealthApplicationFormTemps',
            reader: {
                type: 'json',
                rootProperty: 'data'
            },
            noCache: false
        }
    }
});
